# Example lurkcoin configuration file.

# The name of this lurkcoin instance. This should not be "lurkcoin" to avoid
# conflicts.
name: Test

# The address and port to bind on.
address: "[::]"
port: 5000

# Alternatively, lurkcoin can bind on a UNIX domain socket.
# network_protocol: unix
# address: "/tmp/lurkcoin.sock"

# TLS (optional).
tls:
    enable: false
    cert_file: /path/to/cert.pem
    key_file: /path/to/key.pem

# The database to use.
database:
    # bbolt (recommended)
    # type: bbolt
    # location: lurkcoin.db

    # Plaintext
    type: plaintext
    location: db.json

# Admin pages (accessible at /admin)
admin_pages:
    enable: true
    users:
        test:
            password_hash: 939409414d6a1f6d2101a174e1a611fbf233fe58aa97959eb44dbc75baed2361affd4f6b8ce23e2f904515e7efc89e91dc61e7f6235c994bb721cdf78ba7c3d9
            password_salt: <salt>
            hash_algorithm: sha512

            # Allow the creation of servers and the editing of their balances.
            allow_editing: true

            # Allows database backups to be downloaded. This also requires
            # allow_editing to be enabled.
            allow_database_download: true

# A logfile to redirect standard output to.
# logfile: /tmp/logfile

# URL redirects. Please don't make redirects that conflict with lurkcoin's
# admin pages or APIs.
redirects:
    /: /admin

# The minimum API version to enable.
# min_api_version: 2

# Suppresses any HTTP-related logs such as TLS handshake errors. This does not
# suppress any logs generated by lurkcoin.
# suppress_http_logs: false

# Disables HTTP keep-alive support.
# disable_http_keepalives: false
